server:
  port: 5770
  servlet:
    encoding:
      charset: UTF-8
      force: true
  error:
    include-message: always

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://cubox-fc2.cu1gpwtzgdz5.ap-northeast-2.rds.amazonaws.com:3306/cki_console
    username: cubox
    password: cubox2022!
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20

  mail:
    host: outbound.daouoffice.com
    port: 25
    username: shpark@cubox.aero
    password: mfa0602@#$&
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

mybatis:
  type-aliases-package: cubox.aero.cmfa.scheduler.model
  configuration:
    map-underscore-to-camel-case: true